### ISSUE TITLE
Font Awesome CDN?

### ISSUE THREAD

**Issue by MvErven** [LotarProject/dokuwiki-plugin-icons#20]
What happend to the Font-Awesome CDN path (location)? The newest icons don't show.

![image](https://user-images.githubusercontent.com/17900348/40350746-f53ee0ee-5daa-11e8-8f26-3d843a7ccea2.png)

**Comment by LotarProject** [comment]
Hi, since last update, Icons plugin include OOTB this font icons:

 - Font Awesome
 - Font Linux
 - Material Icons
 - RPG Awesome
 - Typicons

This solution reduce the delay and increase page loading speed.

See https://github.com/LotarProject/dokuwiki-plugin-icons/tree/master/assets assets directory.

At your disposal,
Joseph

**Comment by MvErven** [comment]
I see. Does this means you need to update the icon-list every time new free icons are available on there site?

I wanted the fa>clock (not the clock-o) and the fa>sync. But I don't see how they come available in my page.

**Comment by MvErven** [comment]
Any follow up on my question?
